[tool.poetry]
name = "paleo-utils"
version = "0.0.1"
description = "Tools for the author to facilitate various tasks in paleontological work, including specimen labels, systematics organization, measurement grids, and imaging utilities."
authors = ["AFg6K7h4fhy2 <127630341+AFg6K7h4fhy2@users.noreply.github.com>"]
license = "Apache-2.0"
packages = [{include = "paleo_utils"}]
include = [
    "paleo_utils/fonts/*.otf"
]


[tool.poetry.dependencies]
python = "^3.12"
pre-commit = "^3.7.0"
pillow = "^11.0.0"
attrs = "^24.2.0"
qrcode = "^8.0"


[tool.poetry.group.test.dependencies]
pytest = "^8.3.3"


[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
