[tool.poetry]
name = "paleo-utils"
version = "0.0.1"
description = "Tools for the author to faciliate various tasks in paleontological work, including specimen labels, systematics organization, measurement grids, and imaging utilities. "
authors = ["AFg6K7h4fhy2 <127630341+AFg6K7h4fhy2@users.noreply.github.com>"]
readme = "README.md"
license = "MIT"
packages = [{include = "paleo_utils"}]

[tool.poetry.dependencies]
python = "^3.12"
pre-commit = "^3.7.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
